
version: 2

models:
  - name: dim_users
    description: ""
    columns:
      - name: user_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: fct_comments
    description: "A starter dbt model"
    columns:
      - name: comment_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: fct_posts
    description: "A starter dbt model"
    columns:
      - name: post_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null